/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.LivroDAO;
import Model.LivroModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Tiago
 */
public class SingleLivro extends javax.swing.JFrame {

    /**
     * Creates new form SingleLivro
     *
     * @param livro
     */
    private LivroModel livro = null;
    private final int idUser;

    public SingleLivro(LivroModel livro, int idUsuario) {
        this.idUser = idUsuario;
        initComponents();
        this.livro = livro;
        populaLivro(livro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloLivro = new javax.swing.JLabel();
        pnImagem = new javax.swing.JPanel();
        imgLivro = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sinopseLivro = new javax.swing.JTextArea();
        btJaLi = new javax.swing.JButton();
        autorLivro = new javax.swing.JLabel();
        paginasLivro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Esse Eu Já Li! - Visualizar Livro");

        tituloLivro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tituloLivro.setForeground(new java.awt.Color(162, 67, 173));
        tituloLivro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        pnImagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(162, 67, 173)));

        javax.swing.GroupLayout pnImagemLayout = new javax.swing.GroupLayout(pnImagem);
        pnImagem.setLayout(pnImagemLayout);
        pnImagemLayout.setHorizontalGroup(
            pnImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnImagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnImagemLayout.setVerticalGroup(
            pnImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnImagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );

        sinopseLivro.setEditable(false);
        sinopseLivro.setColumns(20);
        sinopseLivro.setForeground(new java.awt.Color(162, 67, 173));
        sinopseLivro.setLineWrap(true);
        sinopseLivro.setRows(5);
        sinopseLivro.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        sinopseLivro.setEnabled(false);
        jScrollPane1.setViewportView(sinopseLivro);

        btJaLi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icones/okicon.png"))); // NOI18N
        btJaLi.setText("Esse Eu Já Li!");
        btJaLi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJaLiActionPerformed(evt);
            }
        });

        autorLivro.setForeground(new java.awt.Color(162, 67, 173));
        autorLivro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        paginasLivro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloLivro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(autorLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(btJaLi, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
            .addComponent(paginasLivro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tituloLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autorLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paginasLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btJaLi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btJaLiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJaLiActionPerformed
        LivroDAO ldao = new LivroDAO();
        ldao.setLivroLido(idUser, livro.getId());
        JOptionPane.showMessageDialog(null, "O livro foi marcado como lido!");
        btJaLi.setEnabled(false);
    }//GEN-LAST:event_btJaLiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SingleLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SingleLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SingleLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SingleLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel autorLivro;
    private javax.swing.JButton btJaLi;
    private javax.swing.JLabel imgLivro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel paginasLivro;
    private javax.swing.JPanel pnImagem;
    private javax.swing.JTextArea sinopseLivro;
    private javax.swing.JLabel tituloLivro;
    // End of variables declaration//GEN-END:variables

    private void populaLivro(LivroModel livro) {
        tituloLivro.setText(livro.getNome());
        autorLivro.setText(livro.getAutor());
        paginasLivro.setText("Número de páginas: " + livro.getPaginas());
        ImageIcon ii = new ImageIcon(getClass().getResource(livro.getImagem()));
        ii.getImage().flush();
        imgLivro.setIcon(ii);
        sinopseLivro.setText(livro.getSinopse());
        if (livro.isLido()) {
            btJaLi.setEnabled(false);
        } else {
            btJaLi.setEnabled(true);
        }
    }
}
